Feature food search
middlewaremonkeys/goodeats pull request #6
Opened 2016-12-02 01:01 UTC by john-packel

Added search box for user to begin by searching for food.

2016-12-02 14:45 UTC, armyf35 requested changes

2016-12-02 14:45 UTC, armyf35 commented on index.html
> +<!DOCTYPE html>
Duplicate file, and not used by anything

2016-12-02 14:45 UTC, armyf35 commented on client/index.html
> +    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-route.js"></script>
I don't see this being used at all currently, am I missing something?

2016-12-02 21:08 UTC, armyf35 approved these changes

2016-12-02 21:08 UTC, merged

2016-12-04 04:42 UTC, john-packel commented
I marked the one not in the client folder with comment code saying you
would delete it, as discussed.

Thanks

On Fri, Dec 2, 2016 at 4:08 PM Sam Phillips <notifications@github.com>
wrote:

> Merged #6 <https://github.com/middlewaremonkeys/goodeats/pull/6>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/middlewaremonkeys/goodeats/pull/6#event-880582168>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ASrLat93XuHuaG1afymtsajNO73tn4_Nks5rEIi8gaJpZM4LCFBl>
> .
>